### ISSUE TITLE
Failed to find boost at need system thread

### ISSUE THREAD

**Issue by 0xShShang** [osu-crypto/MultipartyPSI#10]
After I excute "cmake .", there occurs an error ：
“-- Could NOT find Boost: missing: system thread (found /usr/local/boost/lib/cmake/Boost-1.79.0/BoostConfig.cmake (found version "1.79.0")) 
CMake Error at cryptoTools/CMakeLists.txt:74 (message): Failed to find boost at Need system thread”

what 's the reason?

**Comment by stellasuc** [comment]
Maybe your system has installed Boost whose version is not right. Then you can remove the Boost in your system.

**Comment by Leonard-Jeffrey** [comment]
Thank you !!!! You are right ! I have fixed it and the reason is exactly what you said.

**Comment by 0xShShang** [comment]
> Maybe your system has installed Boost whose version is not right. Then you can remove the Boost in your system.

Thank you !!!! You are right ! I have fixed it and the reason is exactly what you said

**Comment by yellow123Nike** [comment]
This is a rough solution，How to ensure boost version compatibility？

**Comment by 0xShShang** [comment]
> 

You can find the right version information in the cmake files.

**Comment by alpnn** [comment]
> This is a rough solution，How to ensure boost version compatibility？

Please check my pull request for my fixing.

**Comment by lushimeng** [comment]
Hello, I also encountered the same problem:  Failed to find boost at need system thread. I uninstalled the old version of boost and installed the new version of boost as mentioned above, but it still doesn’t work.

![image](https://github.com/osu-crypto/MultipartyPSI/assets/64461623/261b5218-fecc-4a73-80c4-e6195cd72734)
